package patterns

func registerStreamingServicePatterns(m *Matcher) {
	AddConstPattern(m, "streaming_service", `(?i)\bnetflix\b`, "Netflix")
	AddConstPattern(m, "streaming_service", `(?i)\bnetflixuhd\b`, "Netflix")
	AddConstPattern(m, "streaming_service", `(?i)\bnf\b`, "Netflix")
	AddConstPattern(m, "streaming_service", `(?i)\bamazon[ ._-]?prime\b`, "Amazon Prime")
	AddConstPattern(m, "streaming_service", `(?i)\bamazon\b`, "Amazon Prime")
	AddConstPattern(m, "streaming_service", `(?i)\bamzn\b`, "Amazon Prime")
	AddConstPattern(m, "streaming_service", `(?i)\bhulu\b`, "Hulu")
	AddConstPattern(m, "streaming_service", `(?i)\bitunes(?:hd)?\b`, "iTunes")
	AddConstPattern(m, "streaming_service", `(?i)\bhditunes\b`, "iTunes")
	AddConstPattern(m, "streaming_service", `(?i)(?:^|[ ._-])ae(?:[ ._-]|$)`, "A&E")
	AddConstPattern(m, "streaming_service", `(?i)\bdisney[ ._-]?plus\b`, "Disney+")
	AddConstPattern(m, "streaming_service", `(?i)\bhbo(?:[ ._-]?max)?\b`, "HBO")
	AddConstPattern(m, "streaming_service", `(?i)\bapple[ ._-]?tv(?:[ ._-]?plus)?\b`, "Apple TV+")
	AddConstPattern(m, "streaming_service", `(?i)\bparamount[ ._-]?plus\b`, "Paramount+")
	AddConstPattern(m, "streaming_service", `(?i)\bnf\b`, "Netflix")
	AddConstPattern(m, "streaming_service", `(?i)\batvp\b`, "Apple TV+")
	AddConstPattern(m, "streaming_service", `(?i)\bbbc\b`, "BBC")
	AddConstPattern(m, "streaming_service", `(?i)\bcbs\b`, "CBS")
	AddConstPattern(m, "streaming_service", `(?i)\babc\b`, "ABC")
	AddConstPattern(m, "streaming_service", `(?i)\bdsnp\b|\bdsny\b`, "Disney+")
	AddConstPattern(m, "streaming_service", `(?i)\bfox\b`, "FOX")
	AddConstPattern(m, "streaming_service", `(?i)\bhmax\b`, "HBO")
	AddConstPattern(m, "streaming_service", `(?i)\bhulu\b`, "Hulu")
	AddConstPattern(m, "streaming_service", `(?i)\bip\b`, "iTunes")
	AddConstPattern(m, "streaming_service", `(?i)\bmtv\b`, "MTV")
	AddConstPattern(m, "streaming_service", `(?i)\bnick\b`, "Nick")
	AddConstPattern(m, "streaming_service", `(?i)\bsho\b`, "Showtime")
}
